name: Coverage Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip

      - name: System deps (mlpack)
        run: |
          sudo apt-get update
          sudo apt-get install -y libmlpack-dev

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
          pip install pytest pytest-cov

      - name: Run tests and collect coverage (CPU only)
        run: |
          pytest --ignore=tests/test_gpu_faiss.py \
                 --cov=blockingpy --cov-branch \
                 --cov-report=xml:coverage.xml --cov-report=term-missing

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.xml
          fail_ci_if_error: true
