name: Publish to PyPI

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine tomli

      - name: Verify version sync
        run: |
          python - <<'PY'
          import tomli, pathlib
          cpu = tomli.loads(pathlib.Path("pyproject.toml").read_text("utf-8"))["tool"]["poetry"]["version"]
          gpu = tomli.loads(pathlib.Path("packages/blockingpy-gpu/pyproject.toml").read_text("utf-8"))["tool"]["poetry"]["version"]
          assert cpu == gpu, f"Version mismatch: blockingpy={cpu} vs blockingpy-gpu={gpu}"
          print("Version:", cpu)
          PY

      - name: Build CPU package
        run: python -m build -o dist .

      - name: Build GPU package
        run: python -m build -o packages/blockingpy-gpu/dist packages/blockingpy-gpu

      - name: Upload to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          twine upload dist/* packages/blockingpy-gpu/dist/*
