name: Run Tests

on:
  push:
    branches: [ main, gpu ]
  pull_request:
    branches: [ main, gpu ]

jobs:
  test-cpu:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Install system dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libmlpack-dev
      - name: Install system dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install mlpack
      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest pytest-cov
      - name: Run CPU tests 
        run: pytest --ignore=tests/test_gpu_faiss_blocker.py

  test-gpu-single:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: blockingpy-gpu
          create-args: python=3.10
          init-shell: bash
          condarc: |
            channels:
              - conda-forge
              - pytorch/label/nightly
              - nvidia
            channel_priority: flexible

      - name: Install FAISS cuVS nightly
        shell: bash -l {0}
        run: |
          micromamba install -n blockingpy-gpu -y \
            -c pytorch/label/nightly -c conda-forge -c nvidia \
            'faiss-gpu-cuvs=1.11.0=py3.10_*_cuda12.4.0_nightly'

      - name: Install base stack (conda)
        shell: bash -l {0}
        run: |
          micromamba install -n blockingpy-gpu -y numpy scipy scikit-learn pandas python-igraph

      - name: Install Python deps (pip)
        shell: bash -l {0}
        run: |
          micromamba run -n blockingpy-gpu pip install annoy hnswlib pynndescent nltk voyager model2vec

      - name: Install blockingpy-gpu
        shell: bash -l {0}
        run: |
          micromamba run -n blockingpy-gpu pip install --no-deps -e packages/blockingpy-gpu

      - name: Run GPU FAISS test file
        shell: bash -l {0}
        run: micromamba run -n blockingpy-gpu pytest tests/test_gpu_faiss_blocker.py -q

